### PR TITLE
Add fish-bd & narwhal

### PR DESCRIPTION
**Pull request by 0rax**
Added [fish-bd](https://github.com/0rax/fish-bd) and [narwhal](https://github.com/0rax/narwhal) to the index

### CODE REVIEW

**Comment by bucaran** [comment]
@0rax Thanks! :+1: 

A few recommendations.

* Add each function to its own file inside the `functions` directory.
* Add a note to the README to indicate users they can install it using `fisher install xxx`

That's it.

**Comment by 0rax** [comment]
Okay, I see.

Just a quick question, is it required to separate functions in different files (for example the `__bd_usage`) in term of autoloading and all as those function are not exposed when it is present in a file inside the `$fish_function_path`.

For example when my `bd.fish` is in my `fish_function_path` the `__bd_usage` is not exposed but can be used internaly by bd.

For example I would prefer to keep a single file version of fish-bd for people installing it manually.

Thanks for your time !

**Comment by bucaran** [comment]
@0rax Fisherman moves all your functions to a path which will be in `fish_function_path` and that causes fish to load the functions lazily, so when the user calls `bd` the first time, all the internal functions are loaded too which is why this works. But if you `functions -e bd` the internal functions are not erased from memory in which they linger until you reload your shell.

> For example I would prefer to keep a single file version of fish-bd for people installing it manually.

In that case, you could add a "cleanup" function inside `bd` that erases all the internal (still public, but you get my point) functions and itself. Not ideal, but if you must have everything in one file, you can at least erase the functions when `bd` exits.

If you add each function to its own file and put it inside `functions`, Fisherman will do that for you.

**Comment by 0rax** [comment]
Ok I see, jsut another quick question, if I do that in an `uninstall.fish` script in my `functions/` dir removing those internal.

From what I understand `uninstall.fish` is called when the plugin is removed (just tested it and it seems to work). Would this be a solution ?

I just would like to keep the usage function confined in bd as I know a a greater part of the userbase just uses it by copying `bd.fish`. I am just trying to understand how to make it the best for both world !

**Comment by bucaran** [comment]
> Ok I see, just another quick question, if I do that in an uninstall.fish script in my functions/ dir removing those internal.

Yes, I think that could work, just a "bit" hacky :wink: 

I'll merge this now, please fix those points and happy fishing.

**Comment by bucaran** [comment]
On more thing, sorry to bother you but would you change the description from:

* Simple docker wrapper (docker, docker-machine & docker-compose)

to 

* Simple docker wrapper

or something else but just as short.

No problem with long lines, but really long lines tend to look bad when using tab completion.

**Comment by 0rax** [comment]
Will update the index file right now and will commit those change in my repos ASAP.

Thanks for your time and yeah sorry, just wanted to be sure that I wont need to drop single file support for `bd` and will use complete separation for `narwhal` !

**Comment by 0rax** [comment]
Seems like there is a small problem, I am unable to install them and the only thing different from any other entry is the leading `/` in the url.

Installing any other plugin works fine. Is this a known issue ?

**Comment by bucaran** [comment]
Just for consistency, we should remove the trailing slash, but that is not a problem. I installed `bd`, and everything seems alright. See attached picture.

screen shot 2016-03-03 at 9 53 58 am

If you can post exactly what you typed, maybe I can figure it out.

**Comment by 0rax** [comment]
That is weird then:

screen shot 2016-03-03 at 01 01 12

**Comment by bucaran** [comment]
Something strange happened and I am not sure why, but I bet `bd` is added to your `$fisher_file` by mistake...

If you remove it from there you should be able to proceed.

**Comment by 0rax** [comment]
Still no chance, my `$fisher_file` only contains a reference to z and it also happen after removing z, the fisherfile and trying to reinsatll bd.

screen shot 2016-03-03 at 01 04 42

**Comment by 0rax** [comment]
Ok so I found out what was the problem, and its pretty much due to my own idioty.

Just cleared eveyrthing and reinsatlled fisherman (with debug & spin) and got this error:
```
▸ Installing bd
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
No plugins were installed.
```
I was able to track it down to my `.gitconfig` which uses
```
[url "git@github.com:"]
   insteadOf = https://github.com/
```
In order to fetch everything from Github using ssh instead of http.

This rewriting might bug when the remode ends with `/`, so yeah I dont know if something can be done to trim trailing slash before installing a software or at least to make sure that no index url have one in order to make sure this does not happen again.

Sorry for the inconvenience.

**Comment by bucaran** [comment]
@0rax No problem! So, the problem is fixed if we remove the trailing slash from here?

**Comment by 0rax** [comment]
Yes it should as I dont have any problem when pulling any other plugin !

**Comment by bucaran** [comment]
Alright, I'll fix it. Thanks @0rax for tracking this down :smile:

**Comment by 0rax** [comment]
Oh and I have just one more question, I am wondering if `fisher install` calls my `Makefile`  when installing the package as it seems that my plugin is installed in the fisherman path but also in a standard manner as if `make install` was called (files are copied to `~/.config/fish/functions`)

**Comment by bucaran** [comment]
@0rax It will call `make`, so only the default target (if any) will run.

If something is running incorrectly, you could add a `@all` target. See [here](https://github.com/edc/bass/blob/master/Makefile) for an example of another working plugin that does this.

**Comment by bucaran** [comment]
> EDIT: just found it in __fisher_path_make.fish, I just need to add a default empty rule to make sure a simple call to make will not trigger an installation and that only a call to make install will trigger it.

You are faster than me :smile:

**Comment by 0rax** [comment]
Thanks for your time, glad I finally got the time to check fisherman out and put my hand back at some fish.

Happy fishing to you !

**Comment by bucaran** [comment]
:tropical_fish:

**Pull request merged**
