### PR TITLE
Add Agnoster to index

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by bucaran** [comment]
@hauleth We need to go through the theme carefuly because something is not working correctly.

screen shot 2016-01-30 at 9 44 21 pm

**Comment by hauleth** [comment]
It is. Only thing that doesn't work is that I should write in README that you should add `DEFAULT_USER` variable.

To use Powerline enabled theme use `agnoster powerline`. 

--
Łukasz Jan Niemier

Dnia 30 sty 2016 o godz. 13:44 Jorge Bucaran <notifications@github.com> napisał(a):

**Comment by bucaran** [comment]
Is there any way we could make it work with powerline by default?

**Comment by hauleth** [comment]
It is done on purpose, as I want it to work nicely even for people without Powerline font. To make it work by default just add `agnoster powerline` to your `config.fish`.

**Comment by bucaran** [comment]
I understand. But what do you think is the most common scenario? I think that's the one we should favor. 

One more question, why would anyone choose not having the Powerline fonts? 

What about recommending people to download the fonts to "get the best from Agnoster"?

**Comment by hauleth** [comment]
There is showcase in README with screenshots.

**Comment by bucaran** [comment]
@hauleth Any chance we could have a version that works more like https://github.com/oh-my-fish/theme-agnoster after the installation (by default)?

**Comment by hauleth** [comment]
To be honest I wanted this to be more like https://github.com/vim-airline/vim-airline so you have Powerline disabled by default and then you can simply enable it if you want to do so.

I am only thinking about making `agnoster <theme>` to set universal variables so it would enable theme globally and won't need to be called inside `config.fish`.

**Comment by bucaran** [comment]
@hauleth I don't know why I close, but do you mind rebasing and sending the PR again?

**Pull request closed without merging**
