### PR TITLE
Add plain

### PR DESCRIPTION
**Pull request by changyuheng**
Add plain

### CODE REVIEW

**Comment by bucaran** [comment]
@changyuheng Thanks! How about adding instructions to the README for fisherman?

We have a simple [template](https://github.com/fishery/prompt) here.

**Comment by changyuheng** [comment]
@bucaran OK refined it. Check it again please.

https://github.com/changyuheng/theme-plain

**Comment by bucaran** [comment]
Perfect thanks. One more thing, in the `fishfile`, you listed `git-util`, but the correct name is `git_util`. This little mistake will cause the install to fail.

**Comment by changyuheng** [comment]
OK I amended it. But it was generated by the template.

**Comment by bucaran** [comment]
OK, I just fixed the template.

By the way, if you are not using any of the git utilities, then you don't need them or the fishfile.

**Comment by changyuheng** [comment]
Thanks @bucaran. I was not sure if I need that or not. Because it was generated so I just left it there. I just deleted it.

**Comment by bucaran** [comment]
Good point, I should remove the fishfile as not everyone may need it.

**Pull request merged**
