### PR TITLE
add vibrant theme to index

### PR DESCRIPTION
**Pull request by derhuerst**

### CODE REVIEW

**Comment by bucaran** [comment]
:+1: Thanks!

**Comment by bucaran** [comment]
[the Vibrant prompt in action](https://asciinema.org/a/38749)

**Comment by bucaran** [comment]
@derhuerst BTW, new in Fisherman, you can share your fish syntax colors too. Basically, create a file `set_color_custom.fish` add:

```fish
function set_color_custom
    set -U fish_color_normal                # ...
    set -U fish_color_command               # ...
    set -U fish_color_param                 # ...
    set -U fish_color_redirection           # ...
    set -U fish_color_comment               # ...
    set -U fish_color_error                 # ...
    set -U fish_color_escape                # ...
    set -U fish_color_operator              # ...
    set -U fish_color_end                   # ...
    set -U fish_color_quote                 # ...
    set -U fish_color_autosuggestion        # ...
    set -U fish_color_valid_path            # ...
    set -U fish_color_cwd                   # ...
    set -U fish_color_cwd_root              # ...
    set -U fish_color_match                 # ...
    set -U fish_color_search_match          # ...
    set -U fish_color_selection             # ...
    set -U fish_pager_color_prefix          # ...
    set -U fish_pager_color_completion      # ...
    set -U fish_pager_color_description     # ...
    set -U fish_pager_color_progress        # ...
    set -U fish_color_history_current       # ...
end
```

No need to define all the colors either.

**Comment by derhuerst** [comment]
> [asciicast]
>
> BTW, you can share your fish syntax colors too.

I don't have any syntax colors. It's `asciicast` that picked those.

**Comment by derhuerst** [comment]
@bucaran Maybe you can help me with a `fish` problem:

I want to add a relative path (`./node_modules/.bin`) to my `$PATH`. But whenever there is no `./node_modules` in my `$PWD`, fish complains. How do I turn that off? :smile:

**Comment by bucaran** [comment]
@derhuerst Are you using fish from HEAD or just 2.2.0??

**Comment by derhuerst** [comment]
@bucaran 

> Are you using fish from HEAD or just 2.2.0?

`fish, version 2.2.0`

Is this going to be fixed in `2.3`? I can also see that [there is not a lot missing to `2.3`](https://github.com/fish-shell/fish-shell/milestones/2.3.0).

**Comment by bucaran** [comment]
You can add the relative path to PATH alright, but it does complain, which is annoying.

To turn it off: `set PATH $PATH ./node_modules/.bin ^ /dev/null`

I am not sure why fish needs to check if the path is valid or not. Maybe we can ask in the [gitter](https://gitter.im/fish-shell/fish-shell) room.

**Comment by derhuerst** [comment]
Thanks :+1:

**Pull request merged**
